<!-- footer start -->
<footer id="footer" class="clearfix">
	<section class="container_12">
		<div class="ruler"></div>

		<!-- text article start -->
		<article class="grid_3">
			<h6>SHORT ABOUT US</h6>
			<p>We are pixel-industry, young innovative team based in Croatia with
				great need for developing beautiful, modern, professional responsive
				websites following the newest web trends.</p>

			<a href="about.html" class="find-out-more">- Find out more -</a>
		</article>
		<!-- text article end -->

		<!-- tweeter feed start -->
		<article class="grid_3 tweets-feed">
			<h6>TWITTER</h6>
			<div class="tweets-list-container"></div>
		</article>
		<!-- tweeter feed end -->

		<!-- Pinterest feed start -->
		<article class="grid_3 social-feed pinterest-feed">
			<h6>PINTEREST</h6>
		</article>
		<!-- Pinterest feed end -->

		<!-- contact section start -->
		<article class="grid_3">
			<h6>CONTACT</h6>
			<p>
				Address: 1600 New Street on The Block<br /> Mountain View, CA
				Beverly 90210
			</p>
			<br />
			<p>Phone: +381 22626 465</p>
			<br /> <a href="#">E-mail: info@moderna.com</a>
		</article>
		<!-- contact section end -->

		<div class="ruler bottom"></div>
	</section>

	<!-- copyright start -->
	<section class="container_12 clearfix">
		<section class="copyright">
			<p>&copy; Copyright &copy; <?php echo date('Y');?>.Company name All rights reserved.</p>
			<a class="to-top-link"><img src="/frontend/img/to-top.png"
				class="to-top" alt="back to top" /></a>
		</section>
	</section>
	<!-- copyright end -->
</footer>
<!-- footer end -->