<!-- sidebar start -->
<aside class="grid_3 aside">

	<!-- sidebar widgets start -->
	<ul class="aside-widgets">
		<!-- categories widget start -->
		<li class="categories">
			<h6>blog categories</h6>
			<ul class="border-list">
				<li><a href="#">Web Design</a></li>
				<li><a href="#">Graphic Design</a></li>
				<li><a href="#">Motion Graphics</a></li>
				<li><a href="#">Photography</a></li>
				<li><a href="#">Uncategorized</a></li>
			</ul>
		</li>
		<!-- categories widget end -->

		<!-- popular posts widget start -->
		<li class="posts">
			<h6>popular posts</h6>
			<ul>
				<li><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing
						elit, sed diam nonummy nibh euismod <span class="text-light">| 22
							MAY, Web Design</span>
				</a></li>
				<li><a href="#">Consectetuer adipiscing elit, sed diam nonummy <span
						class="text-light">| 21 JAN, Photography</span></a></li>
				<li><a href="#">Beauty In Red <span class="text-light">| 21 APR,
							Motion Graphics</span></a></li>
			</ul>
		</li>
		<!-- popular posts widget end -->

		<!-- archives widget start -->
		<li class="archives">
			<h6>archives</h6>
			<ul class="border-list">
				<li><a href="#">January 2012 <span class="text-light">(3)</span></a></li>
				<li><a href="#">December 2011 <span class="text-light">(2)</span></a></li>
				<li><a href="#">November 2011 <span class="text-light">(1)</span></a></li>
				<li><a href="#">October 2011 <span class="text-light">(4)</span></a></li>
				<li><a href="#">September 2011 <span class="text-light">(12)</span></a></li>
				<li><a href="#">Jun 2012 <span class="text-light">(1)</span></a></li>
				<li><a href="#">May 2012 <span class="text-light">(3)</span></a></li>
			</ul>
		</li>
		<!-- archives widget end -->
	</ul>
	<!-- sidebar widgets end -->
</aside>
<!-- sidebar end -->