
<section class="scrollable wrapper">
	<div class="row">
		<div class="col-lg-12">
			<!-- .breadcrumb -->
						<?php //echo $this->navigation('navigation')->breadcrumbs()->setPartial('breadcrumb')->setMinDepth(0)->render(); ?>
						<!-- / .breadcrumb -->
		</div>

		<div class="col-sm-12">
			<section class="panel panel-default">
				<header class="panel-heading"> All article except Trash files </header>
				<div class="row wrapper">
					<div class="col-sm-5 m-b-xs">
						<select class="chosen-select" style="width: 200px">
							<option value="0">Bulk action</option>
							<option value="1">Trash selected</option>
							<option value="2">Delete selected</option>
						</select>
					</div>

					<div class="col-sm-3 col-sm-offset-4">
						<div class="input-group">
							<input type="text" class="input-sm form-control"
								placeholder="Search"> <span class="input-group-btn">
								<button class="btn btn-sm btn-default" type="button">Go!</button>
							</span>
						</div>
					</div>
				</div>
				<div class="table-responsive">
					<table class="table table-striped b-t b-light">
						<thead>
							<tr>
								<th width="20"><label class="checkbox m-n i-checks"> <input
										type="checkbox"><i></i></label></th>
								<th>标题</th>
								<th>作者</th>
								<th>分类</th>
								<th>标签</th>
								<th>添加时间</th>
							</tr>
						</thead>
						<tbody>
                        	<?php foreach ($this->posts as $post):?>
                        	<tr>
								<th><label class="checkbox m-n i-checks"> <input type="checkbox"
										name="id[]" value="<?php echo $post->getId()?>"><i></i></label></th>
								<td>
                                    		      <?php echo $post->getTitle()?>
                                    		      <div><?php echo $post->getDescription()?></div>
									<div>
										<a class="text-success"
											href="<?php echo $this->url('admin/post/operation',array('action' => 'edit' ,'id' => $post->getId()))?>"><i
											class="fa fa-edit"></i> Edit</a> | <a class="text-danger"
											href="<?php echo $this->url('admin/post/operation',array('action' => 'trash' ,'id' => $post->getId()))?>"><i
											class="fa fa-trash-o"></i> Trash</a> | <a
											class="text-primary" href=""><i class="i i-eye"></i> View</a>
									</div>
								</td>
								<td><?php echo $post->getAuthor();?></td>
								<td><?php echo $this->category($post->getCatid());?></td>
								<td>标签</td>
                                    		<?php $status = $post->getPublished() ? "success" : "danger"?>
                                    		<td>
                                                <?php echo $this->jhaDate($post->getCreatedtime(),'auto')?>
                                                <p>
										<a class="btn btn-<?php echo $status;?> btn-xs"><i
											class="i i-publish"></i> Publish</a>
									</p>
								</td>
							</tr>
                        	<?php endforeach;?>
                    	</tbody>
					</table>
				</div>

				<footer class="panel-footer">
					<div class="row">
						<div class="col-sm-4 hidden-xs">
							<select class="input-sm form-control input-s-sm inline v-middle">
								<option value="0">Bulk action</option>
								<option value="1">Trash selected</option>
								<option value="2">Delete selected</option>
							</select>
							<button class="btn btn-sm btn-default apply">Apply</button>
						</div>
						<?php //echo $this->paginationcontrol($this->posts, 'Sliding', 'backend/pagination', array('route'=>'admin/paginator','controller'=>'post','action'=>'index'))?>
					</div>
				</footer>
			</section>
		</div>
	</div>
</section>
<script type="text/javascript">
<!--
seajs.use('/sea/pages/post');
//-->
</script>