
<section class="scrollable wrapper">
	<div class="row">
		<div class="col-lg-12">
			<!-- .breadcrumb -->
			<?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('breadcrumb')->setMinDepth(0)->render(); ?>
			<!-- / .breadcrumb -->
		</div>

		<div class="col-sm-12">
			<section class="panel panel-default">
				<header class="panel-heading"> All article except Trash files </header>
				<div class="row wrapper">
					<div class="col-sm-5 m-b-xs">
						<select class="input-sm form-control input-s-sm inline v-middle">
							<option value="0">Bulk action</option>
							<option value="1">Trash selected</option>
							<option value="2">Delete selected</option>
						</select>
						<button class="btn btn-sm btn-default apply">Apply</button>
					</div>
					<div class="col-sm-4 m-b-xs">
						<div class="btn-group" data-toggle="buttons"></div>
					</div>
					<div class="col-sm-3">
						<div class="input-group">
							<input type="text" class="input-sm form-control"
								placeholder="Search"> <span class="input-group-btn">
								<button class="btn btn-sm btn-default" type="button">Go!</button>
							</span>
						</div>
					</div>
				</div>
				<div class="table-responsive">
					<table class="table table-striped b-t b-light">
						<thead>
							<tr>
								<th><label class="checkbox m-n i-checks"> <input type="checkbox"><i></i></label></th>
								<th>标题</th>
								<th>发布</th>
								<th>添加时间</th>
								<th>修改时间</th>
								<th>删除</th>
								<th>还原</th>
							</tr>
						</thead>
						<tbody>
                        	<?php foreach ($this->posts as $post):?>
                        	<tr>
								<th><label class="checkbox m-n i-checks"> <input type="checkbox"
										name="id[]" value="<?php echo $post->getId()?>"><i></i></label></th>
								<td><?php echo $post->getTitle()?></td>
								<td><?php echo $post->getPublished() ? "是" : "否"?></td>
								<td><?php echo date('Y-m-d H:i',$post->getCreatedtime())?></td>
								<td><?php echo date('Y-m-d H:i',$post->getUpdatedtime())?></td>
								<td><a class="active"
									href="<?php echo $this->url('admin/post/operation',array('action' => 'delete' ,'id' => $post->getId()))?>"><i
										class="i i-cross2 text-danger text-active"></i></a></td>
								<td><a class="active"
									href="<?php echo $this->url('admin/post/operation',array('action' => 'undo' ,'id' => $post->getId()))?>"><i
										class="fa fa-undo text-success text-active"></i></a></td>
							</tr>
                        	<?php endforeach;?>
                    	</tbody>
					</table>
				</div>

				<footer class="panel-footer">
					<div class="row">
						<div class="col-sm-4 hidden-xs">
							<select class="input-sm form-control input-s-sm inline v-middle">
								<option value="0">Bulk action</option>
								<option value="1">Trash selected</option>
								<option value="2">Delete selected</option>
							</select>
							<button class="btn btn-sm btn-default apply">Apply</button>
						</div>
					</div>
				</footer>
			</section>
		</div>
	</div>
</section>
