<aside class="bg-black aside-md hidden-print hidden-xs" id="nav">
	<section class="vbox">
		<section class="w-f scrollable">
			<div class="slim-scroll" data-disable-fade-out="true" data-distance="0" data-size="10px" data-railOpacity="0.2" >
				<div class="clearfix wrapper dk nav-user hidden-xs">
					<div class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="thumb avatar pull-left m-r"><img src="/images/a0.png" class="dker" alt="..."><i class="on md b-black"></i></span>
                            <span class="hidden-nav-xs clear"> 
                                <span class="block m-t-xs"><strong class="font-bold text-lt"><?php echo $this->identity();?></strong><b class="caret"></b></span>
                                <span class="text-muted text-xs block">Art Director</span>
                            </span>
						</a>
						<ul class="dropdown-menu animated fadeInRight m-t-xs">
							<li><span class="arrow top hidden-nav-xs"></span> <a href="#">Settings</a></li>
							<li><a href="profile.html">Profile</a></li>
							<li><a href="#"> <span class="badge bg-danger pull-right">3</span> Notifications </a></li>
							<li><a href="docs.html">Help</a></li>
							<li class="divider"></li>
							<li><a href="<?php echo $this->url('auth',array('action'=>'logout'));?>" data-2toggle="ajaxModal">Logout</a></li>
						</ul>
					</div>
				</div>
				<!-- nav -->
				<nav class="nav-primary hidden-xs">
                	<div class="text-muted text-sm hidden-nav-xs padder m-t-sm m-b-sm">Start</div>
                	<ul class="nav nav-main" data-ride="animated">
                        <?php if($this->container):?>
                        <?php foreach ($this->container as $page) :?>
                        <li <?php if($page->isActive(true)):?> class="active" <?php endif;?>>
                			<a href="<?php echo $page->getHref();?>" class="<?php echo $page->getClass();?>">
                                <?php if($page->hasPages()):?>
                                <span class="pull-right text-muted"> <i class="i i-circle-sm-o text"></i> <i class="i i-circle-sm text-active"></i></span>
                                <?php endif;?>
                                <!-- <b class="badge bg-danger pull-right">4</b>  --> 
                                <i class="<?php echo $page->get('icon');?> icon"> </i> 
                                <span class="font-bold"><?php echo $page->getLabel();?></span>
                		    </a>
                            <?php if($page->hasPages()):?>
                            <ul class="nav dk">
                                <?php foreach($page->getPages() as $child):?>
                                <li <?php if($child->isActive(true)):?> class="active"<?php endif;?>>
                                    <a href="<?php echo $child->getHref();?>" class="<?php echo $child->getClass();?>">
                                        <i class="i i-dot"></i><span><?php echo $child->getLabel();?></span>
                                    </a>
                                </li>
                                <?php endforeach;?>
                            </ul>
                            <?php endif;?>
                		</li>
                        <?php endforeach;?>
                        <?php endif;?>
                	</ul>
                	<div class="line dk hidden-nav-xs"></div>
                </nav>
				<!-- / nav -->
			</div>
		</section>
		<footer class="footer hidden-xs no-padder text-center-nav-xs">
			<a href="<?php echo $this->url('auth', array('action' => 'logout'));?>" data-2toggle="ajaxModal" class="btn btn-icon icon-muted btn-inactive pull-right m-l-xs m-r-xs hidden-nav-xs">
				<i class="i i-logout"></i>
			</a>
			<a data-toggle="class:nav-xs" class="btn btn-icon icon-muted btn-inactive m-l-xs m-r-xs">
			    <i class="i i-circleleft text"></i>
			    <i class="i i-circleright text-active"></i>
			</a>
		</footer>
	</section>
</aside>
