<div class="col-sm-4 text-center">
	<small class="text-muted inline m-t-sm m-b-sm">showing <?php echo $this->firstItemNumber;?>-<?php echo $this->lastItemNumber;?> of <?php echo $this->totalItemCount;?> items</small>
</div>

<?php if($this->pageCount):?>
<!-- pagination start -->
<div class="col-sm-4 text-right text-center-xs">
	<ul class="pagination pagination-sm m-t-none m-b-none">
		<?php if($this->previous):?>
		<?php $url = $this->url($this->route,array('action'=>$this->action,'page'=>$this->previous));?>
		<li><a href="<?php echo $url;?>"><i class="fa fa-chevron-left"></i></a></li>
		<?php endif;?>
		<?php foreach ($this->pagesInRange as $page):?>
		<?php $url = $this->url($this->route,array('action'=>$this->action,'page'=>$page));?>
		<?php if($page == $this->current):?>
		<li class="active"><a><?php echo $page;?></a></li>
		<?php else:?>
		<li><a href="<?php echo $url;?>"><?php echo $page;?></a></li>
	    <?php endif;?>
		<?php endforeach;?>
		<?php if ($this->next):?>
	    <?php $url = $this->url($this->route,array('action'=>$this->action,'page'=>$this->next));?>
		<li><a href="<?php echo $url;?>"><i class="fa fa-chevron-right"></i></a></li>
		<?php endif;?>
	</ul>
</div>
<?php endif;?>
