<?php echo $this->doctype(); ?>
<html lang="en" class="app">
<head>
<?php
echo $this->headMeta()
    ->setCharset('UTF-8')
    ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1') . "\n";
$this->headTitle('Scale | Web Application')
    ->setSeparator(' - ')
    ->setAutoEscape(true);
echo $this->headtitle('Zend Framework 2') . "\n";
echo $this->headlink()
    ->appendStylesheet($this->basepath() . '/css/bootstrap.css')
    ->appendStylesheet($this->basepath() . '/css/animate.css')
    ->appendStylesheet($this->basepath() . '/css/font-awesome.min.css')
    ->appendStylesheet($this->basepath() . '/css/icon.css')
    ->appendStylesheet($this->basepath() . '/css/font.css')
    ->appendStylesheet($this->basepath() . '/css/app.css')
    ->appendStylesheet($this->basepath() . '/sea/tools/formelement/datepicker/datepicker.css')
    ->appendStylesheet($this->basepath() . '/sea/tools/formelement/slider/slider.css')
    ->appendStylesheet($this->basepath() . '/sea/tools/formelement/chosen/chosen.css')
    ->appendStylesheet($this->basepath() . '/sea/tools/editable/bootstrap-editable.css')
    ->appendStylesheet($this->basepath() . '/sea/tools/formelement/calendar/bootstrap_calendar.css') . "\n";

echo $this->headScript()
    ->appendFile($this->basePath() . '/js/ie/html5shiv.js'  , 'text/javascript', array('conditional' => 'lt IE 9'))
    ->appendFile($this->basePath() . '/js/ie/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
    ->appendFile($this->basePath() . '/js/ie/excanvas.js'   , 'text/javascript', array('conditional' => 'lt IE 9'))
    ->appendFile($this->basePath() . '/sea/sea-debug.js')
    ->appendFile($this->basePath() . '/sea/config.js')
        ;
?>
</head>
<body>
	<section class="vbox">
        <?php echo $this->partial('header');?>
        <section>
			<section class="hbox stretch">
				<!-- .aside 导航-->
                <?php echo $this->navigation('navigation')->menu()->setPartial('navigation')->render();?>
                <!-- /.aside -->
				<section id="content">
					<section class="vbox">
						<header class="header bg-white b-b b-light">
							<p>
								Welcome back, <?php echo $this->identity()?>, <i
									class="fa fa-map-marker fa-lg text-primary"></i> New York City
							</p>
						</header>
						
                        <?php echo $this->content; ?>
                        <!--footer class="footer bg-white b-t b-light">
                            <p>Welcome back, John Smith, <i class="fa fa-map-marker fa-lg text-primary"></i> New York City</p>
                        </footer-->
					</section>
					<a class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
				</section>
			</section>
		</section>
	</section>
	<?php echo $this->inlinescript();?>
</body>
</html>
